version: '3'
sudo: required
services:
    - docker

before_install:
    - docker build -t cyeluri/docker-react -f Dockerfile.dev .

script:
    - docker run cyeluri/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-1-979027046501"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"
