version: '3'
sudo: required
services:
    - docker

before_install:
    - docker build -t cyeluri/docker-react -f Dockerfile.dev .

script:
    - docker run cyeluri/docker-react npm run test -- --coverage
